name: Image build

on:
  workflow_call:

jobs:
  base_image_build:
    name: Base image build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download ui image
        run: |
          docker pull ghcr.io/macro-deck-app/configservice-ui-base:latest

      - name: Log into docker registry
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779
        with:
          registry: docker.io
          username: suchbyte
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build . --file src/MacroDeck.ConfigService/Dockerfile --tag suchbyte/macro-deck-configservice:${{ github.sha }}
      
      - name: Push the Docker image
        run: docker push suchbyte/macro-deck-configservice:${{ github.sha }}