name: Deploy production

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_image:
    name: Build image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    
  deploy_production:
    name: Deploy production
    needs: [ build_image ]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses:  Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.LIVE_DEPLOY_HOST }}
          user: ${{ secrets.LIVE_DEPLOY_USER }}
          key: ${{ secrets.LIVE_DEPLOY_KEY }}
          known-hosts: ${{ secrets.LIVE_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: config-service