name: Deploy test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'

jobs:
  build_image:
    name: Build image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    
  deploy_develop:
    name: Deploy test
    needs: [ build_image ]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses:  Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.TEST_DEPLOY_HOST }}
          user: ${{ secrets.TEST_DEPLOY_USER }}
          key: ${{ secrets.TEST_DEPLOY_KEY }}
          known-hosts: ${{ secrets.TEST_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: config-service
