name: Deploy test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_image:
    name: Build image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    
  deploy_develop:
    name: Deploy test
    needs: [ build_image ]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.GITHUBWORKFLOWS_USER }}
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          script: |
            cd "scripts/ConfigService/"
            ./update_develop.sh ${{ github.sha }}
